CREATE TABLE IF NOT EXISTS `restaurant`.`CLIENT_FEATURES` (
  `CLIENT_ID` INT NOT NULL,
  `FACEBOOK` VARCHAR(250) NULL,
  `FOURSQUARE` VARCHAR(250) NULL,
  `YELP` VARCHAR(250) NULL,
  PRIMARY KEY (`CLIENT_ID`),
  CONSTRAINT `CLIENT_FEATURES_FK`
    FOREIGN KEY (`CLIENT_ID`)
    REFERENCES `restaurant`.`CLIENT` (`CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);