CREATE TABLE IF NOT EXISTS `restaurant`.`ITEM_CATEGORY_RELATION` (
  `CATEGORY_ID` INT NOT NULL,
  `ITEM_ID` INT NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`, `ITEM_ID`),
  INDEX `CATEGORY_MENU_RELATION_FK2_idx` (`ITEM_ID` ASC),
  CONSTRAINT `CATEGORY_MENU_RELATION_FK1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `restaurant`.`CLIENT_CATEGORY` (`CATEGORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CATEGORY_MENU_RELATION_FK2`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `restaurant`.`MENU` (`ITEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);