CREATE TABLE IF NOT EXISTS `food`.`MENU` (
  `ITEM_ID` INT NOT NULL,
  `ITEM_NAME` VARCHAR(250) NULL,
  `ITEM_IMAGE` BLOB NULL,
  `ITEM_DESC` VARCHAR(500) NULL,
  `ITEM_PRICE` DOUBLE NULL,
  PRIMARY KEY (`ITEM_ID`));