CREATE TABLE IF NOT EXISTS `food`.`USER` (
  `USER_ID` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `MIDDLE_NAME` VARCHAR(100) NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(250) NULL,
  `STATUS` VARCHAR(20) NULL,
  `CREATED_BY` VARCHAR(50) NULL,
  `CREATED_DATE` DATETIME NULL,
  `ROLE` VARCHAR(45) NULL,
  `USER_TYPE` VARCHAR(1) NULL,
  `CLIENT_ID` INT NULL,
  PRIMARY KEY (`USER_ID`));